name: Deployment workflow
on: [push]
jobs:
  build-taro-webapp:
    name: build dist
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[publish]')"
    timeout-minutes: 20
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      -
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: '${{ runner.os }}-node-${{ hashFiles(''**/package.json'') }}'
          restore-keys:

      - name: Install tarojs cli
        run: 'npm install -g @tarojs/cli@2.0.0-beta.9'
      -
        name: Install Dependency
        run: 'npm install'
      -
        name: Build dist
        run: 'npm run build:h5'
      -
        name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shenzhen.aliyuncs.com
          access-key-id: '${{ secrets.OSS_KEY_ID }}'
          access-key-secret: '${{ secrets.OSS_KEY_SECRET }}'
      -
        name: Copy files to aliyun OSS
        run: 'ossutil cp -rf ./dist/ oss://lzc001/'
